server:
  port: 38082

spring:
  data:
    redis:
      host: localhost
      database: 0
logging:
  level:
    com.apzda: trace

apzda:
  cloud:
    captcha:
      props:
        test-mode: "true"
      remove-on-invalid: true
