server:
  port: 8080
spring:
  application:
    name: captcha-service
  messages:
    basename: messages-captcha
  data:
    redis:
      host: redis
      database: 0

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

apzda:
  cloud:
    captcha:
      expired: 120s

logging:
  level:
    com.apzda: debug
